import React from "react";
import { Link } from "react-router-dom";
import "./Home.css";


export default function Home() {
  return (
    <div className="home-container ">
      
      {/* ---------- HERO SECTION ---------- */}
      <section id="home" className="hero fade-in">
        <div className="hero-content">
          <h1>Create a stunning <span>Resume</span> instantly — with AI</h1>
          <p>
            Fill your details, generate AI-powered resumes, and download PDFs instantly.
            Save your templates and access them anytime after login.
          </p>
          <Link to="/generate" className="btn-primary">
            Generate Resume
          </Link>
        </div>
        

        <div className="hero-preview ">
          <div className="preview-card">
            <div className="resume-paper">
              <div className="resume-header">
                <div className="resume-body">
            <h4>OMKAR PAWAR — Web Developer</h4>
            <p><strong>SUMMERY:</strong> Creative Web Developer skilled in React, Node, MongoDB.</p>
            <p><strong>EXPERINCE:</strong> Frontend Engineer at XYZ</p>
            <p><strong>SKILLS:</strong> React · Node · MongoDB</p>
            <p><strong>EDUCATION:</strong> B.C.A in Computer Applications</p>
            <p><strong>PROJECTS:</strong> Portfolio Website, Resume-AI</p>
            <p><strong>CERTIFICATION:</strong> AWS Certified Developer, Java certification</p>
            <p style={{fontSize:14,color:'#888',marginTop:8}}>Generated on: {new Date().toLocaleDateString()}</p>
            <p style={{fontSize:14,color:'#888'}}>This is a sample resume generated by ResumeAI.</p>
            <p style={{fontSize:14,color:'#888'}}>For demo purposes only.</p>
            <p style={{fontSize:14,color:'#888'}}>create your own resume at <Link to="/generate">ResumeAI</Link></p>
            <p style={{fontSize:14,color:'#888'}}>Built with ❤ by Omkar Pawar</p>
            <p style={{fontSize:14,color:'#888'}}>Contact: <a href="mailto:pawaromkar030@gmail.com">pawaromkar030@gmail.com</a></p>
            <p style={{fontSize:14,color:'#888'}}>© 2025 ResumeAI</p>
            <p style={{fontSize:14,color:'#999'}}>Note: This is a fictional resume for demonstration purposes.</p>
          </div>
        </div>
        </div>
        </div>
        </div>
      </section>
      {/* ---------- TEMPLATES PREVIEW ---------- */}
      {/* ---------- TEMPLATES PREVIEW ---------- */}
<section className="templates-preview fade-in" id="templates">
  <h2>Resume Templates Preview</h2>
  <div className="slider-container">
    <div className="slider-track">
      <div className="template-card ">
        <div className="template-thumb temp1"></div>
        <p>Modern Template</p>
      </div>
      <div className="template-card">
        <div className="template-thumb temp2"></div>
        <p>Classic Template</p>
      </div>
      <div className="template-card">
        <div className="template-thumb temp3"></div>
        <p>Creative Template</p>
      </div>
      <div className="template-card">
        <div className="template-thumb temp4"></div>
        <p>Professional Template</p>
      </div>
      {/* repeat for infinite effect */}
      <div className="template-card">
        <div className="template-thumb temp1"></div>
        <p>Modern Template</p>
      </div>
      <div className="template-card">
        <div className="template-thumb temp2"></div>
        <p>Classic Template</p>
      </div>
    </div>
  </div>
</section>

      {/* ---------- FAQ ---------- */}
      <section className="faq-section fade-in neon-border" id="faq">
        <h2>Frequently Asked Questions</h2>
        <div className="faq content">
          <p><strong>1. Is ResumeAI free to use?</strong><br />Yes, you can generate and download resumes for free.</p>
          <p><strong>2. Can I save my resumes?</strong><br />Yes, once you sign up, you can save multiple resumes.</p>
          <p><strong>3. Can I edit my resumes later?</strong><br />Yes, you can re-generate and edit anytime.</p>
          <p><strong>4. Do I need an account?</strong><br />No account is needed for basic use; sign up to save resumes.</p>
          <p><strong>5. How secure is my data?</strong><br />We prioritize your privacy and do not share your data.</p>
          <p><strong>6. Can I use it on mobile?</strong><br />Yes, ResumeAI is mobile-friendly and works on all devices.</p>
          <p><strong>7. What templates are available?</strong><br />We offer Modern, Classic, Creative, and Professional templates.</p>
          <p><strong>8. How to contact support?</strong><br />Email us at <a href="mailto:support@resumeai.com">support@resumeai.com</a></p>
          <p><strong>9. Can I contribute to ResumeAI?</strong><br />Yes, ResumeAI is open-source. Check out our GitHub repository to contribute.</p>
          <p><strong>10. Where can I find the source code?</strong><br />The source code is available on <a href="https://github.com/omkarpawar/resume-ai" target="_blank" rel="noopener noreferrer">GitHub</a>.</p>
          <p><strong>11. Who developed ResumeAI?</strong><br />ResumeAI was developed by Omkar Pawar, a passionate web developer.</p>
          <p><strong>12. What technologies were used?</strong><br />ResumeAI is built using React for the frontend, Node.js for the backend, and MongoDB for data storage.</p>
        </div>
      </section>

      {/* ---------- ABOUT ---------- */}
      <section className="about-section fade-in" id="about">
        <h2>About Me</h2>
        <p>
          Hi 👋, I’m Omkar Pawar — a passionate Web Developer who loves building full-stack
          web apps using React, Node.js, and MongoDB. ResumeAI helps students create
          professional resumes effortlessly using AI.
          <br /><br />
          I built ResumeAI to simplify resume creation for students and job seekers.
          It uses AI to generate tailored resumes based on your input, making the process quick and easy.
          <br /><br />
          I am constantly improving ResumeAI and adding new features.
          It is an open-source project, and you can find the code on <a href="https://github.com/omkarpawar/resume-ai" target="_blank" rel="noopener noreferrer">GitHub</a>.
          <br /><br />
          Feel free to reach out at <a href="mailto:pawaromkar030@gmail.com">pawaromkar030@gmail.com</a>
          for any questions or feedback!
          I hope ResumeAI helps you land your dream job. 🚀
          I appreciate your support!
          I am Omkar Pawar, and this is my passion project.
        
        </p>
      </section>

      {/* ---------- CONTACT ---------- */}
      <section className="contact-section fade-in" id="contact">
        <h2>Contact</h2>
        <p>Email: <a href="mailto:pawaromkar030@gmail.com">pawaromkar030@gmail.com</a></p>
        <div className="social-links">
          <a href="https://linkedin.com" target="_blank" rel="noreferrer">
            <i className="fab fa-linkedin"></i>
          </a>
          <a href="https://twitter.com" target="_blank" rel="noreferrer">
            <i className="fab fa-twitter"></i>
            </a>
          <a href="https://github.com" target="_blank" rel="noreferrer">
            <i className="fab fa-github"></i>
          </a>
          <a href="https://instagram.com" target="_blank" rel="noreferrer">
            <i className="fab fa-instagram"></i>
            </a>
          
            <a href="https://wa.me/yourphonenumber" target="_blank" rel="noreferrer">
            <i className="fab fa-whatsapp"></i>
          </a>
        </div>
      </section>
      { /* ---------- Features ---------- */ }
      <section className="features-section fade-in" id="features">
        <h2>Key Features</h2>
        <div className="features">
          <div className="feature">
            <i className="fas fa-check-circle"></i>
            <p>AI-Powered Suggestions</p>
          </div>
          <div className="feature">
            <i className="fas fa-check-circle"></i>
            <p>Customizable Templates</p>
          </div>
          <div className="feature">
            <i className="fas fa-check-circle"></i>
            <p>One-Click Download</p>
          </div>
          <div className="feature">
            <i className="fas fa-check-circle"></i>
            <p>Cloud Storage</p>
          </div>
          <div className="feature">
            <i className="fas fa-check-circle"></i>
            <p>Real-time Collaboration</p>
          </div>
          <div className="feature">
            <i className="fas fa-check-circle"></i>
            <p>Multi-Device Access</p>
          </div>
          <div className="feature">
            <i className="fas fa-check-circle"></i>
            <p>Secure Data Handling</p>
          </div>
        </div>
      </section>

      {/* ---------- FOOTER ---------- */}
      <footer>
        <p>© 2025 ResumeAI — Built with 💙 by Omkar Pawar</p>
        <p>Contact: <a href="mailto:pawaromkar030@gmail.com">pawaromkar030@gmail.com</a></p>
      </footer>
    </div>
  );
}